name: Create GitHub Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build package
        run: uv build

      - name: Get version
        id: check-version
        run: |
          echo version=$(uv run python -c "import importlib.metadata; print(importlib.metadata.version('indiapins'))") >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.check-version.outputs.version }}
          artifacts: "dist/*"
          token: ${{ secrets.TOKEN }}
